# Generated by Django 4.2.5 on 2023-09-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='nsme',
            new_name='name',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='school.discipline'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='student',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='school.student'),
            preserve_default=False,
        ),
    ]
